CREATE TABLE features (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE subscriptions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  plan VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE POLICY IF NOT EXISTS select_features ON features FOR SELECT USING (TRUE);
CREATE POLICY IF NOT EXISTS insert_features ON features FOR INSERT WITH CHECK (TRUE);
CREATE POLICY IF NOT EXISTS update_features ON features FOR UPDATE USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY IF NOT EXISTS delete_features ON features FOR DELETE USING (TRUE);

CREATE POLICY IF NOT EXISTS select_users ON users FOR SELECT USING (TRUE);
CREATE POLICY IF NOT EXISTS insert_users ON users FOR INSERT WITH CHECK (TRUE);
CREATE POLICY IF NOT EXISTS update_users ON users FOR UPDATE USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY IF NOT EXISTS delete_users ON users FOR DELETE USING (TRUE);

CREATE POLICY IF NOT EXISTS select_subscriptions ON subscriptions FOR SELECT USING (TRUE);
CREATE POLICY IF NOT EXISTS insert_subscriptions ON subscriptions FOR INSERT WITH CHECK (TRUE);
CREATE POLICY IF NOT EXISTS update_subscriptions ON subscriptions FOR UPDATE USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY IF NOT EXISTS delete_subscriptions ON subscriptions FOR DELETE USING (TRUE);